
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: danilo
      POSTGRES_PASSWORD: danilo17
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: danilo@example.com
      PGADMIN_DEFAULT_PASSWORD: danilo17
    ports:
      - "8081:80"  # Cambia el puerto local a 8081 para evitar conflictos con 8080
    depends_on:
      - postgres

volumes:
  postgres_data: